# Generated by Django 4.2.1 on 2023-07-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(default='low', on_delete=django.db.models.deletion.CASCADE, to='todos.priority'),
        ),
    ]
