# Generated by Django 4.2.1 on 2023-07-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_parent_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='value',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
    ]
