# Generated by Django 4.2.1 on 2023-07-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_priority_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='todos',
        ),
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.ManyToManyField(related_name='label', to='todos.label'),
        ),
    ]
