# Generated by Django 4.2.1 on 2023-07-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_remove_label_todos_todo_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, related_name='label', to='todos.label'),
        ),
    ]
